channels:
- conda-forge
dependencies:
- python=3.11.13
- pip<=25.1
- pip:
  - mlflow==2.22.1
  - cloudpickle==3.1.1
  - numpy==2.3.1
  - pandas==2.2.3
  - psutil==7.0.0
  - pyarrow==19.0.1
  - scikit-learn==1.7.1
  - scipy==1.16.0
name: mlflow-env
