model:
  best_model: RandomForest
  feature_sets:
    selected_features:
    - sqft_living
    - bedrooms
    - bathrooms
    - grade
    - view
  mae: 12006.666666666668
  name: house_price_model
  parameters:
    bootstrap: true
    ccp_alpha: 0.0
    criterion: squared_error
    max_depth: 15
    max_features: 1.0
    max_leaf_nodes: null
    max_samples: null
    min_impurity_decrease: 0.0
    min_samples_leaf: 1
    min_samples_split: 2
    min_weight_fraction_leaf: 0.0
    monotonic_cst: null
    n_estimators: 150
    n_jobs: null
    oob_score: false
    random_state: null
    verbose: 0
    warm_start: false
  r2_score: 0.9923079254541115
  rmse: 18928.616049662898
  target_variable: price
