model_type: RandomForestRegressor

hyperparameters:
  n_estimators: 100
  max_depth: 10
  random_state: 42

target_column: price
features:
  - sqft_living
  - bedrooms
  - bathrooms
  - grade
  - view
  - house_age
  - price_per_sqft
  - bed_bath_ratio
